In [28]:
import networkx
import numpy as np

In [2]:
mesh = networkx.Graph()

In [ ]:
mesh.nodes = mesh.add_nodes_from([
    (1, {'number': 1}),
    (2, {'number': 2}),
    (3, {'number': 1}),
])

In [27]:
mesh.nodes[1]

{'number': 1}

In [46]:
x = np.empty(3)

In [48]:
x[:] = np.nan

In [50]:
x = np.full(3, np.nan)

In [51]:
x

array([nan, nan, nan])

In [55]:
type(slice(1, 2))

slice

In [59]:
mesh.add_edge(1, 2, test='hi')

In [61]:
mesh.edges[(1, 2)]

{'test': 'hi'}

In [63]:
x = np.array([1, 2])
y = np.array([3, 4])
np.array([x, y]).T

array([[1, 3],
       [2, 4]])

In [64]:
type(None)

NoneType

In [65]:
x, y = (1, 2)

In [66]:
x

1

In [67]:
(1,1) + (2,2)

(1, 1, 2, 2)

In [69]:
np.array(['test', 'tester']) + np.array(['tester', 'test'])

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('<U6')) -> None

In [71]:
x = np.array(['test', 'tester'])

In [78]:
def test():
    return 1

In [79]:
test(None)

TypeError: test() takes 0 positional arguments but 1 was given

In [80]:
x = np.zeros((12, 12))

In [82]:
x[[1, 3],[1, 2]]

array([0., 0.])

In [83]:
G = networkx.Graph()
G.add_edge(1, 2)
G.add_edge(2, 3)
G.add_edge(3, 4)
G.add_edge(3, 1)

In [86]:
for (u, v) in G.edges:
    print(type(u))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [88]:
G.nodes[1]

{}

In [92]:
slice(0, 2, 1)

slice(0, 2, 1)